[package]
name = "web2pod"
version = "0.1.0"
authors = ["Tim Abell <tim@timwise.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
